server:
  port: 8080
  compression:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  web:
    resources:
      static-locations: classpath:/static/
    mvc:
      static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7